### ISSUE TITLE
✈ Node Blog 2.0 is in progress! 

### ISSUE THREAD

**Issue by bs32g1038** [bs32g1038/node-blog#20]
### Roadmap

- [x] 完整的测试代码
- [x] 优化部分代码
   - [x] react-admin 目录结构重构
   - [x] react-admin 新版ui界面类ant pro
   - [x] react-music-app 优化
   - [x] react-blog 代码优化
- [x] 后台界面设计优化
- [x] 完善的readme.md
- [x] 更多的功能特性
    - [x] react-blog 移动端支持
- [x] bug fix
    - [x] 检测系统相关bug
- [x] update docs

### 环境

操作系统：支持 macOS，Linux，Windows

运行环境：Node.js建议选择 LTS 版本，最低要求 8.x。

数据库： MongoDB 最低要求 4.x 。

---

Operating System: Linux, OS X or Windows.

Node.js Runtime: 8.x or newer; it is recommended that you use LTS Releases.

database: mongdb 4.x or newer;
