### ISSUE TITLE
feat: add the function of admin pages

### ISSUE THREAD

**Issue by bs32g1038** [bs32g1038/node-blog#55]
- [x] all pages batch delete feature
    - [x] add article batch delete function support (#60) 
    - [x] add comment batch delete function support (#62)
    - [x] add category batch delete function support (#64)
    - [x] add demo batch delete function support (#65)
    - [x] add file batch delete function support (#66)
